Name: cc_3d_sys2
# Chiplet + 3D memory

Chip:
  area: 100
  mac_ratio: 0.55
  operational_intensity: 256
  # macs_density: # mm2/TOPS
    # - 0.72
  macs_density: # mm2/TOPS
    - 0.5
  w_per_tops: # w/TOPS
    - 0.36
  other_area: # mm2
    - 10
  core_area_ratio:
    - 0.95
  mem_3d_vaults: [12]
  mem_3d_vault_tsvs: [128]
  pkg2pkg_io: # 300 GB/s per chip per direction
    io_type: 'p2p'
    num: 2
    bandwidth_per_io: 150.0e+9
    area_per_io: 5.0 # ??
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns

Package:
  num_chips: 16
  mem_3d:
    - mem_type: '3D DRAM'
      config: '128 TSVs'
      simulator: False
      layer_area: 4.0
      layer_cost: 0.625
      density: 47757234 # bytes/mm2
      tsv_area: 0.0097
      num_layers: 8
      tsvs: 128
      bit_rate: 17.2e+9 
      pj_per_bit: 1.6

Server:
  packages_per_lane: 2
  num_lanes: 2
  package_max_power_factor: 100.0
  custom_max_power: 100000
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 150.0e+9
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns
  
# System configuration for each model
System:
  all:
   - num_servers: [2, 4, 8, 16]
     eval_len: [[256, 64], [64, 256], [1024, 256], [256, 1024]]
     compute_perf_efficiency: 1.0
     io_bandwidth_efficiency: 1.0
     weight_bandwidth_efficiency: 1.0
     allreduce_algo: 'local_ring_16'
     max_batch: 128
     # default_mapping:
     #  - t: 16
     #    p: 16
     #    micro_batch: 0
     #    prefill_micro_batch: 0

