Name: dram_3d_160tsvs

Chip:
  area: 600
  mac_ratio: 0.8
  operational_intensity: 256
  macs_density: # mm2/TOPS
    - 0.72
  other_area: # mm2
    - 70
  core_area_ratio:
    - 0.95
  mem_3d_vaults: [64]
  mem_3d_vault_tsvs: [160]
  pkg2pkg_io: # 300 GB/s per chip per direction
    io_type: 'p2p'
    num: 2
    bandwidth_per_io: 150.0e+9
    area_per_io: 5.0 # ??
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns

Package:
  num_chips: 1
  custom_max_power_density: 1
  mem_3d:
    # 3D DRAM, 8 layers, 40 MB per layer (similar to HBM3e)
    # Bandwidth options: 60 - 120 GB/s/mm2
    # Cost options: $5 - $10 per GB
    #               $0.195 - $0.39 per 40MB
    # Energy options: 15 - 25 pJ/Byte
    # - mem_type: '3D DRAM'
    #   config: '3D DRAM'
    #   simulator: False
    #   layer_bytes: 41943040 # 40 MB
    #   layer_area: 1.0
    #   layer_cost: [0.195, 0.26, 0.325, 0.39]
    #   num_layers: 8
    #   # bandwidth: [64424509440, 85899345920, 107374182400, 126799200000]
    #   bandwidth: 107374182400
    #   pj_per_byte: [15.0, 17.0, 19.0, 21.0, 23.0, 25.0]
    - mem_type: '3D DRAM'
      config: '64 TSVs'
      simulator: False
      layer_area: 4.0
      layer_cost: 0.75
      density: 47757234 # bytes/mm2
      tsv_area: 0.0097
      num_layers: 8
      tsvs: 64
      bit_rate: 17.2e+9 
      pj_per_bit: 1.6
    - mem_type: '3D DRAM'
      config: '96 TSVs'
      simulator: False
      layer_area: 4.0
      layer_cost: 0.75
      density: 47757234 # bytes/mm2
      tsv_area: 0.0097
      num_layers: 8
      tsvs: 96
      bit_rate: 17.2e+9 
      pj_per_bit: 1.6
    - mem_type: '3D DRAM'
      config: '128 TSVs'
      simulator: False
      layer_area: 4.0
      layer_cost: 0.75
      density: 47757234 # bytes/mm2
      tsv_area: 0.0097
      num_layers: 8
      tsvs: 128
      bit_rate: 17.2e+9 
      pj_per_bit: 1.6
    - mem_type: '3D DRAM'
      config: '160 TSVs'
      simulator: False
      layer_area: 4.0
      layer_cost: 0.75
      density: 47757234 # bytes/mm2
      tsv_area: 0.0097
      num_layers: 8
      tsvs: 160
      bit_rate: 17.2e+9 
      pj_per_bit: 1.6
    - mem_type: '3D DRAM'
      config: '192 TSVs'
      simulator: False
      layer_area: 4.0
      layer_cost: 0.75
      density: 47757234 # bytes/mm2
      tsv_area: 0.0097
      num_layers: 8
      tsvs: 192
      bit_rate: 17.2e+9
      pj_per_bit: 1.6
    - mem_type: '3D DRAM'
      config: '224 TSVs'
      simulator: False
      layer_area: 4.0
      layer_cost: 0.75
      density: 47757234 # bytes/mm2
      tsv_area: 0.0097
      num_layers: 8
      tsvs: 224
      bit_rate: 17.2e+9
      pj_per_bit: 1.6

Server:
  packages_per_lane: 2
  num_lanes: 2
  package_max_power_factor: 100.0
  custom_max_power: 100000
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 150.0e+9
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns
  
# System configuration for each model
System:
  all:
   - num_servers: 6
     eval_len: [[256, 64]]
     compute_perf_efficiency: 1.0
     io_bandwidth_efficiency: 1.0
     weight_bandwidth_efficiency: 1.0
     allreduce_algo: '3d_ring'
     default_mapping:
      - t: 24
        p: 1
        micro_batch: 0
        prefill_micro_batch: 0

