Name: mem_3d_explore

Chip:
  perf:
    # - 138000000000000 # 138 TOPS
    - 70000000000000 # 70 TOPS
  sram:
    # - 144000000 # 144 MB
    - 72000000 # 72 MB
  sram_bw:
    # - 2000000000000 # 2 TB/s
    - 1000000000000 # 1 TB/s
  macs_density: # mm2/TOPS
    - 1.0
  mem_3d_vaults: [32]
  pkg2pkg_io:
    io_type: 'p2p'
    num: 8
    bandwidth_per_io: 12500000000 # 12.5 GB/s
    area_per_io: 0.3
    tdp_per_io: 0.125

Package:
  num_chips: 1
  mem_3d:
    # HMC 2.0, 8 layers 32 MB per vault
    - mem_type: 'HMC'
      simulator: False
      layer_bytes: 33554432 # 32 MB
      layer_area: 2.1
      layer_cost: 0.23 # same $/GB as HBM2
      num_layers: 8
      bandwidth: 10737418240 # 10 GB/s 
      bandwidth_efficiency: 0.8
      pj_per_byte: 31.2 # same as HBM2
    # 3D SRAM, based on AMD's 3D V-Cache
    - mem_type: '3D SRAM'
      simulator: False
      layer_bytes: 8388608 # 8 MB
      layer_area: 5.1 # 41mm2 with 8 vaults
      layer_cost: 1.875 # 41mm2 costs ~$15 in 7nm, 15/8 = $1.875
      num_layers: 1
      bandwidth: 274877906944 # 256 GB/s
      bandwidth_efficiency: 0.8
      pj_per_byte: 1.25

Server:
  packages_per_lane: [4, 5, 6]
  custom_max_power: 4000
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 12500000000

