Name: sram_5nm
# Based on tpuv5p

Chip:
  sram_tech: '5nm'
  area: 600
  mac_ratio: 0.06
  operational_intensity: 4
  macs_density: # mm2/TOPS
    - 0.72
  other_area: # mm2
    - 70
  core_area_ratio:
    - 0.95
  pkg2pkg_io: # 300 GB/s per chip per direction
    io_type: 'p2p'
    num: 2
    bandwidth_per_io: 150.0e+9
    area_per_io: 5.0 # ??
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns

Package:
  num_chips: 1

Server:
  packages_per_lane: 2
  num_lanes: 2
  package_max_power_factor: 100.0
  custom_max_power: 100000
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 150.0e+9
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns
  
# System configuration for each model
System:
  all:
   - num_servers: 93
     eval_len: [[64, 256]]
     compute_perf_efficiency: 1.0
     io_bandwidth_efficiency: 1.0
     weight_bandwidth_efficiency: 1.0
     allreduce_algo: '2d_ring'
     default_mapping:
      - t: 372
        p: 1
        micro_batch: 0
        prefill_micro_batch: 0

