Name: sram_3d_explore

Chip:
  # perf:
  #   # - 138000000000000 # 138 TOPS
  #   - 70000000000000 # 70 TOPS
  # sram:
  #   # - 144000000 # 144 MB
  #   - 72000000 # 72 MB
  # sram_bw:
  #   # - 2000000000000 # 2 TB/s
  #   - 1000000000000 # 1 TB/s
  macs_density: # mm2/TOPS
    - 0.72
  core_area_ratio:
    - 0.6
  area: [200]
  mac_ratio:  [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10, 0.12, 0.16, 0.20, 0.24, 0.28, 0.32, 0.40, 0.50]
  operational_intensity: [1.0, 1.25, 1.5, 1.75, 2.0, 4.0, 8.0, 16.0, 32.0]
  mem_3d_vaults: [16, 32, 39, 64]
  pkg2pkg_io:
    io_type: 'p2p'
    num: 16
    bandwidth_per_io: 12500000000 # 12.5 GB/s
    area_per_io: 0.3
    tdp_per_io: 0.125

Package:
  num_chips: 1
  mem_3d:
    # 3D SRAM, based on AMD's 3D V-Cache
    - mem_type: '3D SRAM'
      simulator: False
      layer_bytes: 8388608 # 8 MB
      layer_area: 5.1 # 41mm2 with 8 vaults
      layer_cost: 1.875 # 41mm2 costs ~$15 in 7nm, 15/8 = $1.875
      num_layers: 1
      bandwidth: 274877906944 # 256 GB/s
      bandwidth_efficiency: 0.8
      pj_per_byte: 1.25

Server:
  packages_per_lane: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  package_max_power_factor: 100.0
  custom_max_power: 6400
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 12500000000

