Name: tpuv4i 

Chip:
  chip_id: 'tpuv4i'
  perf: # 138 TOPS
    - 138000000000000
  sram: # 144 MB
    - 144000000
  sram_bw: # 2 TB/s
    - 2000000000000
  macs_density: # mm2/TOPS
    - 0.72
  other_area: # mm2
    - 200
  core_area_ratio:
    - 0.95
  hbm_channels: 8
  pkg2pkg_io:
    io_type: 'p2p'
    num: 4
    bandwidth_per_io: 25000000000
    area_per_io: 0.3
    tdp_per_io: 0.125

Package:
  num_chips: 1
  hbm:
    # HBM2, 8 layers, 8 GB, 614 GB/s
    - config: 'TPUv4i_HBM2_8GB'
      simulator: False
      channel_bytes: 1073741824 # 1 GB
      channel_width: 128
      num_channels: 8
      bit_rate: 5150605312 # to make the whole stack 614 GB/s
      bandwidth_efficiency: 0.8

Server:
  packages_per_lane: 2
  num_lanes: 2
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 12500000000

