Name: v100

Chip:
  chip_id: 'v100'
  perf: # 112 TOPS
    - 112.0e+12
  sram: # 300 MB ??
    - 300.0e+6
  sram_bw: # 2 TB/s ??
    - 2.0e+12
  macs_density: # mm2/TOPS
    - 0.5
  w_per_tops: # w/TOPS
    - 0.36
  other_area: # mm2
    - 70
  core_area_ratio:
    - 0.95
  hbm_channels: 32
  pkg2pkg_io: # 300 GB/s per chip per direction
    io_type: 'p2p'
    num: 1
    bandwidth_per_io: 16.0e+9
    area_per_io: 5.0 # ??
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns

Package:
  num_chips: 1
  hbm:
    # HBM2, 8 channels, 1 GB/channel, 900/4 = 225 GB/s
    - config: 'v100_HBM2'
      simulator: False
      channel_bytes: 1073741824 # 1 GB
      channel_width: 128
      num_channels: 8
      bit_rate: 1887436800 # to make the whole stack 225 GB/s
      stack_cost: 120

Server:
  packages_per_lane: 2
  num_lanes: 2
  package_max_power_factor: 100.0
  custom_max_power: 100000
  io:
    io_type: 's2s'
    num: 1
    bandwidth_per_io: 16.0e+9
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns
  

# System configuration for each model
System:
  all:
   - num_servers: 1
     eval_len: [[20, 8], [60, 20], [128, 8], [256, 64], [64, 256]]
     compute_perf_efficiency: 1
     io_bandwidth_efficiency: 1
     weight_bandwidth_efficiency: 1
     allreduce_algo: 'ring'
     default_mapping:
      - t: 4
        p: 1
        micro_batch: 0
        prefill_micro_batch: 0


