Name: tpuv4
# https://cloud.google.com/tpu/docs/system-architecture-tpu-vm#tpu_v4
# Paper: https://arxiv.org/ftp/arxiv/papers/2304/2304.01433.pdf

Chip:
  chip_id: 'tpuv4'
  tech: '7nm'
  dataflow: 'roofline' # 'roofline' for the roofline model, or 'WS' for weight-stationary
  # dataflow: 'WS'
  freq: 1.05e+9
  bytes_per_word: 2 # bfloat16 or fp16

  perf: 275.0e+12
  sram: 300.0e+6
  sram_bw: 2.0e+12

  # num_sa: 8 
  num_sa: 1 # number of systolic arrays
  acc_depth: 1000000000 # accumulation depth for systolic array, now assume it's infinite

  other_area: 200
  core_area_ratio: 0.95

  hbm_channels: 32
  pkg2pkg_io: # 1.1 PB/s all-reduce bandwidth per Pod, 281 GB/s per chip
    io_type: 'p2p'
    num: 2
    bandwidth_per_io: 135.0e+9
    area_per_io: 5.0 # ??
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit

Package:
  num_chips: 1
  hbm:
    # HBM2, 8 channels, 8 GB, 300 GB/s
    - config: 'TPUv4_HBM2_32GB'
      simulator: False
      channel_bytes: 1073741824 # 1 GB
      channel_width: 128
      num_channels: 8
      bit_rate: 2343750000 # to make the whole stack 300 GB/s

Server:
  packages_per_lane: 2
  num_lanes: 2
  thermal_eval: False # whether to evaluate the thermal
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 135.0e+9
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit



