Name: b200

Chip:
  chip_id: 'b200'
  tech: '5nm'
  dataflow: 'roofline' # 'roofline' for the roofline model, or 'WS' for weight-stationary
  freq: 1.0e+9 # frequency, in Hz
  bytes_per_word: 2 # bfloat16 or fp16

  perf: 1125.0e+12 # 1125 TOPS
  sram: 125.0e+6 # 100 MB
  sram_bw: 4.0e+12 # 4 TB/s

  other_area: 80 # mm2
  core_area_ratio: 0.95

  hbm_channels: 32

  pkg2pkg_io: # 300 GB/s per chip per direction
    io_type: 'p2p'
    num: 2
    bandwidth_per_io: 150.0e+9
    area_per_io: 5.0 # ??
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns

  macs_density: 0.5 # mm2/TOPS
  w_per_tops: 0.36 # w/TOPS

Package:
  num_chips: 2
  hbm:
    # HBM3e, 8 layers, 24 GB, 1178 GB/s
    - config: 'HBM3E'
      simulator: False
      channel_bytes: 3221225472 # 3 GB or 24 Gb
      channel_width: 128
      num_channels: 8
      bit_rate: 9878424780 # 9.2 Gb/s
      stack_cost: 120
      pj_per_byte: 24 # 3 pJ/bit

Server:
  packages_per_lane: 2
  num_lanes: 2
  thermal_eval: False # whether to evaluate the thermal
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 150.0e+9
    tdp_per_io: 0.25 # 
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns
