Name: hbm_explore
# Based on tpuv5p

Chip:
  tech: '7nm'
  dataflow: 'roofline' # 'roofline' for the roofline model, or 'WS' for weight-stationary
  freq: 1.0e+9
  bytes_per_word: 2 # bfloat16 or fp16j

  perf: 459.0e+12 # 459 TOPS
  sram: 300.0e+6 # 300 MB
  sram_bw: 2.0e+12 # 2 TB/s

  other_area: 70 # mm2
  core_area_ratio: 0.95

  hbm_channels: 48

  pkg2pkg_io: # 300 GB/s per chip per direction
    io_type: 'p2p'
    num: 2
    bandwidth_per_io: 150.0e+9
    area_per_io: 5.0 # ??
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns

Package:
  num_chips: 1
  thermal_eval: False # whether to evaluate the thermal
  hbm:
    # associated exploration
    associated_explore: 'config'
    config: ['HBM2E', 'HBM3', 'HBM3E']
    simulator: False
    channel_bytes: 2147483648 # 2 GB or 16 Gb
    channel_width: 128
    num_channels: {'HBM2E': 8, 'HBM3': 8, 'HBM3E': 12}
    bit_rate: {'HBM2E': 3435973836, 'HBM3': 6871947673, 'HBM3E': 9878424780}
    stack_cost: 120
    pj_per_byte: {'HBM2E': 31, 'HBM3': 24, 'HBM3E': 24}

Server:
  packages_per_lane: 2
  num_lanes: 2
  thermal_eval: False # whether to evaluate the thermal
  io:
    io_type: 's2s'
    num: 2
    bandwidth_per_io: 150.0e+9
    tdp_per_io: 0.25 # ??
    pj_per_byte: 9.36 # GRS is 1.17pj/bit
    init_time: 10.0e-9 # 10 ns
  